# Generated by Django 4.1.2 on 2023-01-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Please add alturnative text', max_length=255, null=True, verbose_name='Alternative text'),
        ),
    ]
